name: Update Java File Count Badge

on:
  push:
    branches:
      - main

jobs:
  update_counts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Count Java files
        id: count_java_files
        run: |
          java_files=$(find . -type f -name '*.java' | wc -l)
          echo "{\"java_files\": $java_files }" > count-java-files.json

      - name: Update Badge
        run: |
          badge_url="https://img.shields.io/badge/dynamic/json?color=blue&label=Java%20Files&query=java_files&url=https://raw.githubusercontent.com/${{ github.repository }}/main/count-java-files.json"
          sed -i "s|!\[Java Files\].*|$badge_url|" README.md

      - name: Commit and Push badge update
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "your.email@example.com"
          git add README.md
          git commit -m "Update Java file count badge [skip ci]"
          git push
