name: Update File Counts

on:
  push:
    branches:
      - main  # Replace 'main' with the default branch of your repository

jobs:
  update_counts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Count Java files
        id: count_java_files
        run: |
          java_files=$(find . -type f -name '*.java' | wc -l)
          echo "Java Files: $java_files" > java_files_badge.md

      - name: Update README.md
        run: |
          python - <<EOF
with open('README.md', 'r') as f:
    content = f.read()
    with open('java_files_badge.md', 'r') as badge_file:
        badge_content = badge_file.read()
    updated_content = content.replace('![Java Files](java_files_badge.md)', badge_content)
with open('README.md', 'w') as f:
    f.write(updated_content)
EOF

      - name: Commit and Push badge update
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "your.email@example.com"
          git add README.md
          git commit -m "Update Java file count badge [skip ci]"
          git push
