name: Update File Counts

on:
  push:
    branches:
      - main  # Replace 'main' with the default branch of your repository

jobs:
  update_counts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Count Java files
  run: |
    java_files=$(find . -type f -name '*.java' | wc -l)
    sed -i "s/Java Files: [0-9]*/Java Files: $java_files/" README.md

      # Add more steps for other file types and directories if needed

      - name: Commit and Push badge updates
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "your.email@example.com"
          git add java_files_badge.md python_files_badge.md js_files_badge.md
          git commit -m "Update file counts badges [skip ci]"
          git push
