name: Update File Counts

on:
  push:
    branches:
      - main  # Replace 'main' with the default branch of your repository

jobs:
  update_counts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Count Java files
        id: count_java_files
        run: |
          java_files=$(find . -type f -name '*.java' | wc -l)
          echo '{"java_files":' $java_files '}' > java_file_count.json

      - name: Update README.md
        run: |
          echo "![Java Files](https://img.shields.io/badge/dynamic/json?color=blue&label=Java%20Files&query=java_files&url=https://raw.githubusercontent.com/${{ github.repository }}/main/java_file_count.json)" > README.md.new
          mv README.md.new README.md

      - name: Commit and Push badge update
        run: |
          git config user.name "Your GitHub Username"
          git config user.email "your.email@example.com"
          git add README.md
          git commit -m "Update Java file count badge [skip ci]"
          git push
